### ISSUE TITLE
Where is (n)VIm config

### ISSUE THREAD

**Issue by Pandademic** [jbuchermn/dotfiles-nix#2]
I'd love to help with the statusline for (n)VIm but can't find you config.Please point me in the right direction

**Comment by jbuchermn** [comment]
Hi, nice! Take a look at https://github.com/jbuchermn/dotfiles-nix/blob/main/users/common/nvim.vim and https://github.com/jbuchermn/dotfiles-nix/blob/main/users/common/nvim.nix
